#
# Beez utils: Makefile
#

include ../Makefile.in

PROJECTNAME="beez-utils"

DIST_FILE=dist/beez-utils/index.js
NONE_RELEASE_FILE=release/beez.utils.js
OPTIMIZE_RELEASE_FILE=release/beez.utils.min.js
