#
# Beez MVCR: Makefile
#

include ../Makefile.in

PROJECTNAME="beez-mvcr"

DIST_FILE=dist/beez-mvcr/index.js
NONE_RELEASE_FILE=release/beez.mvcr.js
OPTIMIZE_RELEASE_FILE=release/beez.mvcr.min.js

testserver:
	@echo "\n\n\t\tTest Server [start]\n\n\n"
	beez-foundation -c spec/foundation/spec.js -a beez:../../../beez

